services:
  jobs:
    build: 
      context: .
      args:
        - NODE_ENV=development
    container_name: "jobs_workers"
    volumes:
      - .:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    depends_on:
      jobs_database:
        condition: service_healthy
    restart: on-failure
    networks:
      - back-tier

  jobs_database:
    image: postgres:14.2
    container_name: "jobs-database"
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${DB_JOB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-tier
      - jobs

volumes:
  db-data: {}
  nodemodules: {}

networks:
  back-tier:
  jobs:
    driver: bridge
    name: jobs
