services:
  cron:
    build:
      context: .
    container_name: "cron"
    env_file:
      - .env
    volumes:
      - cron_nodemodules:/usr/src/app/node_modules
    restart: on-failure
    networks:
      - jobs

volumes:
  cron_nodemodules: {}

networks:
  jobs:
    external: true
    name: jobs
