services:
  jobs_database:
    image: postgres:14.2
    container_name: "jobs-database"
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/schema:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iaes
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jobs:
    build: 
      context: .
    container_name: "jobs_workers"
    env_file:
      - ./.env
    depends_on:
      jobs_database:
        condition: service_healthy
    restart: on-failure
    network_mode: host

    